### PR TITLE
initial documentation for g.raphael

### PR DESCRIPTION
**Pull request by qoelet**
hi dmitry,

here's the set of documentation for g.raphael (pretty basic outline, some in-depth coverage for g.line.js and g.pie.js). perhaps this can be helpful to beginners in getting started. will work on getting more examples up and elaborate on g.dot.js, and g.barchart.js in the next few weeks, plus cover some of the helper functions in g.raphael.js.

let me know what's missing and how i might improve this further.

thanks!
kenny

### CODE REVIEW

**Comment by devth** [comment]
+1

Would love to see some docs for g.raphael.

**Comment by joekarl** [comment]
Yeah, some documentation would be great....

**Comment by naoisegolden** [comment]
+1 it's a first nice step. Documentation MUCH needed!

**Comment by imod** [comment]
there seems not a lot of interest in getting g.raphael any further...
last commit... 2 moths ago
most pull requests waiting since a couple of months - should we still use it?

**Comment by qoelet** [comment]
@imod, I would honestly look at other alternatives at this point, I remember Dmitry mentioning that he will not be maintaining it on Twitter some weeks back.

**Comment by naoisegolden** [comment]
@kennyshen he is no longer a commiter, but told me that it is a live product. I recently used it and was buggy and lacked features, but I am not sure there is anything much better than this...

**Comment by qoelet** [comment]
@naoisegolden You could give Highcharts a try.

**Pull request closed without merging**
